themes:
  dark-mode:
    primary-color: "#5f819d" # Primary (most of the UI)
    primary-background-color: "#282a2e" # Primary background colour (dialogs, e.t.c)
    secondary-background-color: "#1d1f21" # Secondary background colour (main UI background)
    paper-card-background-color: "#1d1f21"
    #paper-item-icon-color: "#5e8d87"
    primary-text-color: "#c5c8c6"
    secondary-text-color: "#707880"
    disabled-text-color: "rgba(255, 255, 255, 0.5)"
    #divider-color: "rgba(255, 255, 255, 0.12)" # Divider colour
    #paper-card-header-color: "#FFFFFF" # Card header text colour
    paper-listbox-background-color: "#1d1f21" # Listbox background colour
    paper-listbox-color: "#c5c8c6" # Listbox text colour
    #paper-grey-200: "#373b41" # Listbox selected item background colour
    ## paper-toggle-button-checked-ink-color: "#1ABA92"
    ## paper-toggle-button-checked-button-color: "#1ABA92"
    ## paper-toggle-button-checked-bar-color: "#1ABA92"
    ## paper-slider-knob-color: "#1ABA92"
    ## paper-slider-knob-start-color: "#1ABA92"
    ## paper-slider-pin-color: "#1ABA92"
    #paper-slider-active-color: "#1d1f21"
    paper-slider-secondary-color: "#1d1f21"
    #table-row-background-color: "transparant"
    #table-row-alternative-background-color: "transparant"
    #sidebar-icon-color: "#EEEEEE"
    #sidebar-selected-icon-color: "#81a2be"
